ExecuteRange_Constants.VALID_SPELLS_IDS = {
	["BLINDSIDE_ID"]=111240,
						
	["SHADOW_WORD_DEATH_ID"]=32379,

    ["HAMMER_OF_WRATH_ID"]=24275,

    ["EXECUTE_FURY_ID"]=5308,
	["EXECUTE_FURY_MASSACRE_ID"]=280735,
	["EXECUTE_ARMS_ID"]=163201,

	["DRAIN_SOUL_ID"]=198590,

	["SOUL_REAPER_ID"]=130736
};

ExecuteRange_Constants.VALID_SPELLS_NAMES_PER_CLASS = {
	["ROGUE"]="Blindside",
	["WARLOCK"]="Drain Soul",
	["PRIEST"]="Drain Soul",
	["DEATHKNIGHT"]="Soul Reaper",
	["WARRIOR"]="Execute",
	["PALADIN"]="Hammer of Wrath",
};

ExecuteRange_Constants.BLINDSIDE_EXECUTE_RANGE = 31; -- it is actually triggered at 31 and below, /shrug
ExecuteRange_Constants.DRAIN_SOUL_EXECUTE_RANGE = 20;
ExecuteRange_Constants.SHADOW_WORD_DEATH_EXECUTE_RANGE = 20;
ExecuteRange_Constants.EXECUTE_RANGE = 20;
ExecuteRange_Constants.EXECUTE_RANGE_MASSACRE = 35;
ExecuteRange_Constants.SOUL_REAPER_EXECUTE_RANGE = 35;
ExecuteRange_Constants.HAMMER_OF_WRATH_EXECUTE_RANGE = 20;

ExecuteRange_Constants.TEXTURES = {
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\ARCANE_MISSILES.BLP"] = "arcane_missiles",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\ARCANE_MISSILES_1.BLP"] = "arcane_missiles_1",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\ARCANE_MISSILES_2.BLP"] = "arcane_missiles_2",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\ARCANE_MISSILES_3.BLP"] = "arcane_missiles_3",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\ART_OF_WAR.BLP"] = "art_of_war",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\BACKLASH.BLP"] = "backlash",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\BACKLASH_GREEN.BLP"] = "backlash_green",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\BANDITS_GUILE.BLP"] = "bandits_guile",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\BERSERK.BLP"] = "berserk",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\BLOOD_BOIL.BLP"] = "blood_boil",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\BLOOD_SURGE.BLP"] = "blood_surge",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\BRAIN_FREEZE.BLP"] = "brain_freeze",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\DARK_TIGER.BLP"] = "dark_tiger",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\DARK_TRANSFORMATION.BLP"] = "dark_transformation",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\DAYBREAK.BLP"] = "daybreak",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\DENOUNCE.BLP"] = "denounce",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\ECHO_OF_THE_ELEMENTS.BLP"] = "echo_of_the_elements",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\ECLIPSE_MOON.BLP"] = "eclipse_moon",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\ECLIPSE_SUN.BLP"] = "eclipse_sun",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\FERAL_OMENOFCLARITY.BLP"] = "feral_omenofclarity",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\FOCUS_FIRE.BLP"] = "focus_fire",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\FROZEN_FINGERS.BLP"] = "frozen_fingers",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\FULMINATION.BLP"] = "fulmination",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\FURY_OF_STORMRAGE.BLP"] = "fury_of_stormrage",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\GENERICARC_01.BLP"] = "genericarc_01",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\GENERICARC_02.BLP"] = "genericarc_02",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\GENERICARC_03.BLP"] = "genericarc_03",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\GENERICARC_04.BLP"] = "genericarc_04",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\GENERICARC_05.BLP"] = "genericarc_05",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\GENERICARC_06.BLP"] = "genericarc_06",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\GENERICTOP_01.BLP"] = "generictop_01",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\GENERICTOP_02.BLP"] = "generictop_02",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\GRAND_CRUSADER.BLP"] = "grand_crusader",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\HAND_OF_LIGHT.BLP"] = "hand_of_light",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\HOT_STREAK.BLP"] = "hot_streak",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\IMPACT.BLP"] = "impact",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\IMP_EMPOWERMENT.BLP"] = "imp_empowerment",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\IMP_EMPOWERMENT_GREEN.BLP"] = "imp_empowerment_green",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\KILLING_MACHINE.BLP"] = "killing_machine",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\LOCK_AND_LOAD.BLP"] = "lock_and_load",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MAELSTROM_WEAPON.BLP"] = "maelstrom_weapon",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MAELSTROM_WEAPON_1.BLP"] = "maelstrom_weapon_1",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MAELSTROM_WEAPON_2.BLP"] = "maelstrom_weapon_2",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MAELSTROM_WEAPON_3.BLP"] = "maelstrom_weapon_3",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MAELSTROM_WEAPON_4.BLP"] = "maelstrom_weapon_4",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MASTER_MARKSMAN.BLP"] = "master_marksman",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MOLTEN_CORE_GREEN.BLP"] = "molten_core_green",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MONK_BLACKOUTKICK.BLP"] = "monk_blackoutkick",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MONK_OX.BLP"] = "monk_ox",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MONK_OX_2.BLP"] = "monk_ox_2",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MONK_OX_3.BLP"] = "monk_ox_3",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MONK_SERPENT.BLP"] = "monk_serpent",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MONK_TIGER.BLP"] = "monk_tiger",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\MONK_TIGERPALM.BLP"] = "monk_tigerpalm",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\NATURES_GRACE.BLP"] = "natures_grace",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\NECROPOLIS.BLP"] = "necropolis",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\NIGHTFALL.BLP"] = "nightfall",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\PREDATORY_SWIFTNESS.BLP"] = "predatory_swiftness",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\RAGING_BLOW.BLP"] = "raging_blow",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\RIME.BLP"] = "rime",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\SERENDIPITY.BLP"] = "serendipity",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\SHADOW_OF_DEATH.BLP"] = "shadow_of_death",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\SHADOW_WORD_INSANITY.BLP"] = "shadow_word_insanity",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\SHOOTING_STARS.BLP"] = "shooting_stars",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\SLICE_AND_DICE.BLP"] = "slice_and_dice",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\SUDDEN_DEATH.BLP"] = "sudden_death",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\SUDDEN_DOOM.BLP"] = "sudden_doom",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\SURGE_OF_DARKNESS.BLP"] = "surge_of_darkness",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\SURGE_OF_LIGHT.BLP"] = "surge_of_light",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\SWORD_AND_BOARD.BLP"] = "sword_and_board",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\THRILL_OF_THE_HUNT_1.BLP"] = "thrill_of_the_hunt_1",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\THRILL_OF_THE_HUNT_2.BLP"] = "thrill_of_the_hunt_2",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\THRILL_OF_THE_HUNT_3.BLP"] = "thrill_of_the_hunt_3",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\TOOTH_AND_CLAW.BLP"] = "tooth_and_claw",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\ULTIMATUM.BLP"] = "ultimatum",
	["TEXTURES\\SPELLACTIVATIONOVERLAYS\\WHITE_TIGER.BLP"] = "white_tiger"
};
table.sort(ExecuteRange_Constants.TEXTURES);

ExecuteRange_Constants.TEXTURE_POSITIONS = {
	["TOP"] = "Top",
	["RIGHT"] = "Right",
	["LEFT"] = "Left",
	["BOTTOM"] = "Bottom",
	["CENTER"] = "Center"
}