ExecuteRange_Core = LibStub("AceAddon-3.0"):NewAddon("ExecuteRange", "AceConsole-3.0", "AceEvent-3.0" );
ExecuteRange_Console = {};
ExecuteRange_DB = {};
ExecuteRange_Constants = {};
ExecuteRange_SettingsFormEvents = {};
ExecuteRange_SpellAlertsHandler = {};
ExecuteRange_ButtonsResolver = {};
ExecuteRange_SlashCommandHandler = {};
ExecuteRange_Settings = {};